### PR TITLE
Update feather-icons

### PR DESCRIPTION
**Pull request by andreasvirkus**
Addresses #12

### CODE REVIEW

**Comment by egoist** [comment]
Can you update lockfile as well?

**Comment by andreasvirkus** [comment]
Also updated poi to `12.2.0` to get rid of a severe-level dependency security issue, which `npm audit` brought up (https://www.npmjs.com/advisories/725).

**Comment by NaseebullahSafi** [comment]
Please, can we get a merge for this? Thanks a bunch!

**Comment by egoist** [comment]
updated to 4.10.0

**Pull request closed without merging**
